services:
  - type: web
    name: youtube-django
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn youtube_harvest.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: youtube_harvest.settings
      - key: PYTHON_VERSION
        value: 3.12
      - fromDotEnv: true
